HRMSPROJECT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings

import hrms

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrms.urls', namespace = 'hrms')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.urls import path
from . import views
from .views import import_api_data_to_excel
app_name = 'hrms'
urlpatterns = [

# Authentication Routes
    path('ad', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('', views.Login_View.as_view(), name='login'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    # path('dashboard/<int:id>', views.get_employee_name, name='dashboard'),

# Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.Employee_Delete.as_view(), name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    # path('dashboard/button-press/', ButtonPressView.as_view(), name='button_press'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),

#Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

#Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),
    path('dashboard/attendance/<int:pk>/in/', views.Attendance_In.as_view(), name='attendance_in'),

#Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

#Recruitment

    path("recruitment/",views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/",views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

#Payroll
    path("employee/pay/",views.Pay.as_view(), name="payroll"),
    path("employee/pay/<int:pk>",views.Pay.as_view(), name="payroll"),


#report
    path('dashboard/report/in/', views.Report.as_view(), name='report'),
#Break
    path('dashboard/break/in/', views.Break_new.as_view(), name='break'),
    path('dashboard/break/<int:pk>/in/', views.Break_in.as_view(), name='break_in'),
    path('dashboard/break/<int:pk>/out/', views.Break_out.as_view(), name='break_out'),


   

        # export to csv 
path('export-csv/', views.export_table_to_csv, name='export_table_to_csv'),

path('export-data/', import_api_data_to_excel, name='import_api_data_to_excel'),


]

hrms/views.py
from django.shortcuts import render,redirect, resolve_url,reverse, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from .models  import User, Department,Kin, Attendance, Leave, Recruitment, Break , breack_status
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import FormView, CreateView,View,DetailView,TemplateView,ListView,UpdateView,DeleteView
from .forms import RegistrationForm,LoginForm,EmployeeForm,KinForm,DepartmentForm,AttendanceForm, LeaveForm, RecruitmentForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q
from datetime import datetime, date,timedelta
from django.shortcuts import  HttpResponse
import csv
import requests
import json
import os
import openpyxl
from django.conf import settings



if len(Attendance.objects.values())==0:
    for i in User.objects.all():
            new = Attendance()
            new.staff = i
            new.status = "ABSENT"
            new.date = date.today()

            new.save()
elif Attendance.objects.values().last()['date'] != date.today() :
    for i in User.objects.all():
        new = Attendance()
        new.staff = i
        new.status = "ABSENT"
        new.date = date.today()
        new.save()
if len(Break.objects.values())==0:
    for i in User.objects.all():
            new = Break()
            new.staff = i
            # new.status = "ABSENT"
            new.date = date.today()

            new.save()
elif Break.objects.values().last()['date'] != date.today() :
    for i in User.objects.all():
        new = Break()
        new.staff = i
        # new.status = "ABSENT"
        new.date = date.today()
        new.save()



# Create your views here.
class Index(TemplateView):
   template_name = 'hrms/home/home.html'

#   Authentication
class Register (CreateView):
    model = get_user_model()
    form_class  = RegistrationForm
    template_name = 'hrms/registrations/register.html'
    success_url = reverse_lazy('hrms:login')
    
class Login_View(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/login.html'

    def get_success_url(self):
        url = resolve_url('hrms:dashboard')
        return url

class Logout_View(View):

    def get(self,request):
        logout(self.request)
        return redirect ('hrms:login',permanent=True)
    

 # Main Board   
class Dashboard(LoginRequiredMixin,ListView,):
    template_name = 'hrms/dashboard/index.html'
    login_url = 'hrms:login'
    model = User
    context_object_name = 'qset'            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['emp_total'] = User.objects.all().filter(is_superuser = 0).count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.filter(is_superuser = 1).count()
        context['workers'] = User.objects.order_by('-id').filter(is_superuser=0)
        return context
   

class Employee_New(CreateView):
    model = get_user_model() 
    form_class = EmployeeForm  
    template_name = 'hrms/employee/create.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'
    success_url = reverse_lazy('hrms:dashboard')
    
    
    
class Employee_All(LoginRequiredMixin,ListView):
    template_name = 'hrms/employee/index.html'
    model = get_user_model()
    login_url = 'hrms:login'
    context_object_name = 'employees'
    paginate_by  = 5
    
class Employee_View(LoginRequiredMixin,DetailView):
    queryset = User.objects.select_related('department')
    template_name = 'hrms/employee/single.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            query = Kin.objects.get(employee=self.object.pk)
            context["kin"] = query
            return context
        except ObjectDoesNotExist:
            return context
        
class Employee_Update(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'hrms/employee/edit.html'
    form_class = EmployeeForm
    login_url = 'hrms:login'
    
    
class Employee_Delete(LoginRequiredMixin,DeleteView):
    pass

class Employee_Kin_Add (LoginRequiredMixin,CreateView):
    model = Kin
    form_class = KinForm
    template_name = 'hrms/employee/kin_add.html'
    login_url = 'hrms:login'
   

    def get_context_data(self):
        context = super().get_context_data()
        if 'id' in self.kwargs:
            emp = User.objects.get(pk=self.kwargs['id'])
            context['emp'] = emp
            return context
        else:
            return context

class Employee_Kin_Update(LoginRequiredMixin,UpdateView):
    model = Kin
    form_class = KinForm
    template_name = 'hrms/employee/kin_update.html'
    login_url = 'hrms:login'

    def get_initial(self):
        initial = super(Employee_Kin_Update,self).get_initial()
        
        if 'id' in self.kwargs:
            emp =  User.objects.get(pk=self.kwargs['id'])
            initial['employee'] = emp.pk
            
            return initial

#Department views

class Department_Detail(LoginRequiredMixin, ListView):
    context_object_name = 'employees'
    template_name = 'hrms/department/single.html'
    login_url = 'hrms:login'
    def get_queryset(self): 
        queryset = User.objects.filter(department=self.kwargs['pk'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dept"] = Department.objects.get(pk=self.kwargs['pk']) 
        return context
    
class Department_New (LoginRequiredMixin,CreateView):
    model = Department
    template_name = 'hrms/department/create.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'

class Department_Update(LoginRequiredMixin,UpdateView):
    model = Department
    template_name = 'hrms/department/edit.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:dashboard')

#Attendance View

class Attendance_New (LoginRequiredMixin,CreateView):
    model = Attendance
    form_class = AttendanceForm
    login_url = 'hrms:login'
    template_name = 'hrms/attendance/create.html'
    success_url = reverse_lazy('hrms:attendance_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["today"] = timezone.localdate()
        pstaff = Attendance.objects.all()


        context['present_staffers'] = pstaff
      



        return context

class Attendance_Out(LoginRequiredMixin,View):
    login_url = 'hrms:login'

    def get(self, request,*args, **kwargs):
       user = Attendance.objects.get(Q(staff__id=self.kwargs['pk']) & Q(date=timezone.localdate()))
       user.last_out = datetime.now()
       user.last = datetime.now()

       user.save()
       user = Attendance.objects.get(Q(staff__id=self.kwargs['pk']) & Q(date=timezone.localdate()))
       user.wh = user.last - user.first
       dt = datetime.strptime(user.TBT, "%H:%M:%S.%f")
       total_sec = dt.hour*3600 + dt.minute*60 + dt.second  # total seconds calculation
       td = timedelta(seconds=total_sec)     
       user.twh = (user.last - user.first) - td
        
       user.save()


       return redirect('hrms:attendance_new')
    


class LeaveNew (LoginRequiredMixin,CreateView, ListView):
    model = Leave
    template_name = 'hrms/leave/create.html'
    form_class = LeaveForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:leave_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["leaves"] = Leave.objects.all()
        return context

class Payroll(LoginRequiredMixin, ListView,):
    model = User
    template_name = 'hrms/payroll/index.html'
    login_url = 'hrms:login'
    context_object_name = 'stfpay'
   
    
class RecruitmentNew (CreateView):
    model = Recruitment
    template_name = 'hrms/recruitment/index.html'
    form_class = RecruitmentForm
    success_url = reverse_lazy('hrms:recruitment')

class RecruitmentAll(LoginRequiredMixin,ListView):
    model = Recruitment
    login_url = 'hrms:login'
    template_name = 'hrms/recruitment/all.html'
    context_object_name = 'recruit'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = requests.get("https://script.googleusercontent.com/macros/echo?user_content_key=U7MEkkhMUwRt3KrET5iL0gkmCzyTKb52PDnjuHi5NlOd6rnzrq2X1PR2zYe1bU9ABXrJRDGw99sDlPhxj3_Khl1HOBbG4P1pm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnAi2aJZGbP2FVRDstJrcUxI3al7Y5mCrv9NHX_PRqzx2tabxNITQD8yd8VLn0xbjSPAFzgbcuN1KEwOFBTjDbW4zpm50RqvrZA&lib=ME2YbkWRlb0EHiAseivp7PHA-nDy3ldf7").json()
        # print(data)
        
        newdata = []
        for i in data:
            newdata.append({"first":i['First Name'],"last": i['Last Name'],"mobile": i['Mobile Number'],"email": i['Personal Email ID'] , "Qualification":i['Qualification'],"Experience":i['Fresher/Experience ']})
        # print(newdata)
        context['data'] = newdata
        return context

class RecruitmentDelete (LoginRequiredMixin,View):
    login_url = 'hrms:login'
    def get (self, request,pk):
     form_app = Recruitment.objects.get(pk=pk)
     form_app.delete()
     return redirect('hrms:recruitmentall', permanent=True)

class Pay(LoginRequiredMixin,ListView):
    model = User
    template_name = 'hrms/payroll/index.html'
    context_object_name = 'emps'
    login_url = 'hrms:login'

class Report(LoginRequiredMixin,ListView):
    model = Attendance
    template_name = 'hrms/attendance/report/index.html'

hrms/templates/hrms/attendance/create.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Attendance| ITSC-HRMS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'hrms:dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Attendance </li>
                    </ol>
                </nav>

                <div class="col-lg-12 grid-margin">
                    {% if user.is_superuser %}
                    <div class="card">

                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa  fa-check-square-o">&emsp; Employee Attendance </i></h4><hr>
                                <!-- <form class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** All Fields are required</small><br>
                                        {{form.errors}}
                                        <div class="table-responsive">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            Date
                                                        </th>
                                                        
                                                        <th>
                                                            Staffer
                                                        </th>
                                                        <th>
                                                            Status
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td class="py-1">
                                                            {{today}}
                                                        </td>
                                                        
                                                        <td>
                                                            {{form.staff}}
                                                        </td>
                                                        <td>
                                                            {{form.status}}
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>

                                        
                                    <div class="text-center mt-3">
                                        <button class="btn btn-rounded btn-outline-success"><i class="mdi mdi-check"></i>Sign in</button></button>
                                    </div>{% endif %}
                                </form><br> -->
                            <!-- <h4 class="text-center text-primary"><i class="fa  fa-sign-in">&emsp; Signed In Staffer(s) </i> </h4><hr> -->
                            {% if present_staffers %}
                            <small class='text-center'>This is a list of staffer(s) that are currently present. </small>
                             <div class="table-responsive">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            Date
                                                        </th>
                                                        <th>
                                                            First-In (Arrival)
                                                        </th>
                                                        <th>
                                                            Last-Out (Departure)
                                                        </th>
                                                        <th>
                                                            Name
                                                        </th>
                                                        <th>
                                                            Action(s)
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% if user.is_superuser%}
                                                    {% for ps in present_staffers %}
                                                        <tr>
                                                            <td class="py-1">
                                                                {{ps.date}}
                                                            </td>
                                                            <td>
                                                            <strong>{{ps.first_in}}</strong>
                                                            </td>
                                                            <td>
                                                            
                                                                <strong>{{ps.last_out }}</strong>
                                                            </td>
                                                            <td>
                                                                {{ps.staff.first_name}} - {{ ps.staff.last_name}}

                                                            </td>
                                                            <td>
                                                                {% comment %} <a href="{% url 'hrms:attendance_out' pk=ps.staff.pk %}" {% if not ps.last_out %} class="btn btn-sm btn-info"  {% endif %} class="btn btn-sm btn-info disabled" > <i class="fa fa-sign-out"></i> Sign-out</a> {% endcomment %}
                                                                <a href="{% url 'hrms:attendance_in' pk=ps.staff.pk %}"  {% if not ps.first_in %} class="btn btn-sm btn-info"  {% endif %} class="btn btn-sm btn-info disabled" > <i class="fa fa-sign-out"></i> Sign-in</a>
                                                                <a href="{% url 'hrms:attendance_out' pk=ps.staff.pk %}"  class="btn btn-sm btn-info " > <i class="fa fa-sign-out"></i> Sign-out</a>
                                                            </td>
                                                        </tr>

                                                    {% endfor %}
                                                    {% else %}
                                                      {% for ps in present_staffers %}
                                                       {% if user.first_name  ==  ps.staff.first_name and user.last_name == ps.staff.last_name%}
                                                        <tr>
                                                            <td class="py-1">
                                                                {{ps.date}}
                                                            </td>
                                                            <td>
                                                            <strong>{{ps.first_in}}</strong>
                                                            </td>
                                                            <td>

                                                                <strong>{{ps.last_out }}</strong>
                                                            </td>
                                                            <td>
                                                            {{ps.staff.first_name}} - {{ps.staff.last_name}}
                                                            </td>
                                                            <td>
                                                                {% comment %} <a href="{% url 'hrms:attendance_out' pk=ps.staff.pk %}" {% if not ps.last_out %} class="btn btn-sm btn-info"  {% endif %} class="btn btn-sm btn-info disabled" > <i class="fa fa-sign-out"></i> Sign-out</a> {% endcomment %}
                                                                <a href="{% url 'hrms:attendance_in' pk=ps.staff.pk %}"  {% if not ps.first_in %} class="btn btn-sm btn-info"  {% endif %} class="btn btn-sm btn-info disabled" > <i class="fa fa-sign-out"></i> Sign-in</a>
                                                                <a href="{% url 'hrms:attendance_out' pk=ps.staff.pk %}"  class="btn btn-sm btn-info " > <i class="fa fa-sign-out"></i> Sign-out</a>
                                                            </td>
                                                        </tr>
                                                       {% endif %}
                                                      {% endfor %}
                                                   {% endif %}
                                                </tbody>
                                            </table>
                                        </div>
                            {% else %}
                                <p class="lead"> There are currently no staffers in the system </p>
                            {% endif %}   
                                
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

hrms/templates/hrms/attendance/edit.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Edit Employee | ITSC-HRMS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-edit">&emsp; Edit Department </i></h4><hr>
                                <form  class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** All Fields are required</small>
                                        {{form.as_p}}
                                    <div class="text-center mt-3">
                                        <button class="btn btn-outline-success btn-rounded"><i class="mdi mdi-cloud-download"></i>Update Department</button></button>
                                        
                                    </div>
                                </form>                   
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

hrms/templates/hrms/attendance/single.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Department Info | ITSC-HRMS {% endblock title %}
{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <span class="lead">{{dept.name | capfirst}} Department <a href="{% url 'hrms:dept_update' dept.pk %}" class="btn btn-rounded btn-success float-right"> <i class="fa fa-edit"></i>  Update Info</a></span><hr>    
                                <div class="row">
                                <!--First Column-->
                                    <div class="col-lg-5">
                                        <div class="card border-left border-info shadow-sm">
                                            <div class="card-body">
                                                <p class="lead">Brief History</p>
                                                <p class='text-justify'>
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, inventore assumenda fugiat repudiandae delectus id libero dolor veritatis natus architecto?
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, inventore assumenda fugiat repudiandae delectus id libero dolor veritatis natus architecto?
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                       <!--Second Column-->
                                    <div class="col-lg-7">
                                        <div class="card border-right border-info shadow-sm">
                                            <div class="card-body">
                                                <p class="lead">Associated Employees</p>
                                                <div class="row">
                                                {% if employees %}
                                                    {% for employee in employees  %}
                                                        <div class="col-lg">
                                                            <div class="card border-bottom border-top border-info">
                                                                <div class="card-body">
                                                                    <div class='text-center'>
                                                                        <img class='img-fluid' src="{{employee.thumb.url}}" width='100' height='100' alt="{{employee.first_name}}">
                                                                        <p>{{employee.last_name|capfirst}}.{{employee.first_name|slice:1}}</p>
                                                                        <p>({{employee.emp_id|capfirst}})</p>
                                                                        <div>
                                                                            <a href="{% url 'hrms:employee_view' pk=employee.pk %}" class=" badge badge-info">view profile</a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    {% endfor %}
                                                {% else %}
                                                    <p class="lead text-center"> No Associated Employee</p>
                                                {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                
                                       
                                
                    </div>                     
                                        
                </div>
            </div>
        </div>
    </div>

{% endblock content %}