HRMSPROJECT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings

import hrms

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrms.urls', namespace = 'hrms')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.urls import path
from . import views
from .views import import_api_data_to_excel
app_name = 'hrms'
urlpatterns = [

# Authentication Routes
    path('ad', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('', views.Login_View.as_view(), name='login'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    # path('dashboard/<int:id>', views.get_employee_name, name='dashboard'),

# Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.Employee_Delete.as_view(), name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    # path('dashboard/button-press/', ButtonPressView.as_view(), name='button_press'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),

#Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

#Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),
    path('dashboard/attendance/<int:pk>/in/', views.Attendance_In.as_view(), name='attendance_in'),

#Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

#Recruitment

    path("recruitment/",views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/",views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

#Payroll
    path("employee/pay/",views.Pay.as_view(), name="payroll"),
    path("employee/pay/<int:pk>",views.Pay.as_view(), name="payroll"),


#report
    path('dashboard/report/in/', views.Report.as_view(), name='report'),
#Break
    path('dashboard/break/in/', views.Break_new.as_view(), name='break'),
    path('dashboard/break/<int:pk>/in/', views.Break_in.as_view(), name='break_in'),
    path('dashboard/break/<int:pk>/out/', views.Break_out.as_view(), name='break_out'),


   

        # export to csv 
path('export-csv/', views.export_table_to_csv, name='export_table_to_csv'),

path('export-data/', import_api_data_to_excel, name='import_api_data_to_excel'),


]

hrms/views.py
from django.shortcuts import render,redirect, resolve_url,reverse, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from .models  import User, Department,Kin, Attendance, Leave, Recruitment, Break , breack_status
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import FormView, CreateView,View,DetailView,TemplateView,ListView,UpdateView,DeleteView
from .forms import RegistrationForm,LoginForm,EmployeeForm,KinForm,DepartmentForm,AttendanceForm, LeaveForm, RecruitmentForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q
from datetime import datetime, date,timedelta
from django.shortcuts import  HttpResponse
import csv
import requests
import json
import os
import openpyxl
from django.conf import settings



if len(Attendance.objects.values())==0:
    for i in User.objects.all():
            new = Attendance()
            new.staff = i
            new.status = "ABSENT"
            new.date = date.today()

            new.save()
elif Attendance.objects.values().last()['date'] != date.today() :
    for i in User.objects.all():
        new = Attendance()
        new.staff = i
        new.status = "ABSENT"
        new.date = date.today()
        new.save()
if len(Break.objects.values())==0:
    for i in User.objects.all():
            new = Break()
            new.staff = i
            # new.status = "ABSENT"
            new.date = date.today()

            new.save()
elif Break.objects.values().last()['date'] != date.today() :
    for i in User.objects.all():
        new = Break()
        new.staff = i
        # new.status = "ABSENT"
        new.date = date.today()
        new.save()



# Create your views here.
class Index(TemplateView):
   template_name = 'hrms/home/home.html'

#   Authentication
class Register (CreateView):
    model = get_user_model()
    form_class  = RegistrationForm
    template_name = 'hrms/registrations/register.html'
    success_url = reverse_lazy('hrms:login')
    
class Login_View(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/login.html'

    def get_success_url(self):
        url = resolve_url('hrms:dashboard')
        return url

class Logout_View(View):

    def get(self,request):
        logout(self.request)
        return redirect ('hrms:login',permanent=True)
    

 # Main Board   
class Dashboard(LoginRequiredMixin,ListView,):
    template_name = 'hrms/dashboard/index.html'
    login_url = 'hrms:login'
    model = User
    context_object_name = 'qset'            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['emp_total'] = User.objects.all().filter(is_superuser = 0).count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.filter(is_superuser = 1).count()
        context['workers'] = User.objects.order_by('-id').filter(is_superuser=0)
        return context
   

class Employee_New(CreateView):
    model = get_user_model() 
    form_class = EmployeeForm  
    template_name = 'hrms/employee/create.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'
    success_url = reverse_lazy('hrms:dashboard')
    
    
    
class Employee_All(LoginRequiredMixin,ListView):
    template_name = 'hrms/employee/index.html'
    model = get_user_model()
    login_url = 'hrms:login'
    context_object_name = 'employees'
    paginate_by  = 5
    
class Employee_View(LoginRequiredMixin,DetailView):
    queryset = User.objects.select_related('department')
    template_name = 'hrms/employee/single.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            query = Kin.objects.get(employee=self.object.pk)
            context["kin"] = query
            return context
        except ObjectDoesNotExist:
            return context
        
class Employee_Update(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'hrms/employee/edit.html'
    form_class = EmployeeForm
    login_url = 'hrms:login'
    
    
class Employee_Delete(LoginRequiredMixin,DeleteView):
    pass

class Employee_Kin_Add (LoginRequiredMixin,CreateView):
    model = Kin
    form_class = KinForm
    template_name = 'hrms/employee/kin_add.html'
    login_url = 'hrms:login'
   

    def get_context_data(self):
        context = super().get_context_data()
        if 'id' in self.kwargs:
            emp = User.objects.get(pk=self.kwargs['id'])
            context['emp'] = emp
            return context
        else:
            return context

class Employee_Kin_Update(LoginRequiredMixin,UpdateView):
    model = Kin
    form_class = KinForm
    template_name = 'hrms/employee/kin_update.html'
    login_url = 'hrms:login'

    def get_initial(self):
        initial = super(Employee_Kin_Update,self).get_initial()
        
        if 'id' in self.kwargs:
            emp =  User.objects.get(pk=self.kwargs['id'])
            initial['employee'] = emp.pk
            
            return initial

#Department views

class Department_Detail(LoginRequiredMixin, ListView):
    context_object_name = 'employees'
    template_name = 'hrms/department/single.html'
    login_url = 'hrms:login'
    def get_queryset(self): 
        queryset = User.objects.filter(department=self.kwargs['pk'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dept"] = Department.objects.get(pk=self.kwargs['pk']) 
        return context
    
class Department_New (LoginRequiredMixin,CreateView):
    model = Department
    template_name = 'hrms/department/create.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'

class Department_Update(LoginRequiredMixin,UpdateView):
    model = Department
    template_name = 'hrms/department/edit.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:dashboard')

#Attendance View

class Attendance_New (LoginRequiredMixin,CreateView):
    model = Attendance
    form_class = AttendanceForm
    login_url = 'hrms:login'
    template_name = 'hrms/attendance/create.html'
    success_url = reverse_lazy('hrms:attendance_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["today"] = timezone.localdate()
        pstaff = Attendance.objects.all()


        context['present_staffers'] = pstaff
      



        return context

class Attendance_Out(LoginRequiredMixin,View):
    login_url = 'hrms:login'

    def get(self, request,*args, **kwargs):
       user = Attendance.objects.get(Q(staff__id=self.kwargs['pk']) & Q(date=timezone.localdate()))
       user.last_out = datetime.now()
       user.last = datetime.now()

       user.save()
       user = Attendance.objects.get(Q(staff__id=self.kwargs['pk']) & Q(date=timezone.localdate()))
       user.wh = user.last - user.first
       dt = datetime.strptime(user.TBT, "%H:%M:%S.%f")
       total_sec = dt.hour*3600 + dt.minute*60 + dt.second  # total seconds calculation
       td = timedelta(seconds=total_sec)     
       user.twh = (user.last - user.first) - td
        
       user.save()


       return redirect('hrms:attendance_new')
    


class LeaveNew (LoginRequiredMixin,CreateView, ListView):
    model = Leave
    template_name = 'hrms/leave/create.html'
    form_class = LeaveForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:leave_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["leaves"] = Leave.objects.all()
        return context

class Payroll(LoginRequiredMixin, ListView,):
    model = User
    template_name = 'hrms/payroll/index.html'
    login_url = 'hrms:login'
    context_object_name = 'stfpay'
   
    
class RecruitmentNew (CreateView):
    model = Recruitment
    template_name = 'hrms/recruitment/index.html'
    form_class = RecruitmentForm
    success_url = reverse_lazy('hrms:recruitment')

class RecruitmentAll(LoginRequiredMixin,ListView):
    model = Recruitment
    login_url = 'hrms:login'
    template_name = 'hrms/recruitment/all.html'
    context_object_name = 'recruit'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = requests.get("https://script.googleusercontent.com/macros/echo?user_content_key=U7MEkkhMUwRt3KrET5iL0gkmCzyTKb52PDnjuHi5NlOd6rnzrq2X1PR2zYe1bU9ABXrJRDGw99sDlPhxj3_Khl1HOBbG4P1pm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnAi2aJZGbP2FVRDstJrcUxI3al7Y5mCrv9NHX_PRqzx2tabxNITQD8yd8VLn0xbjSPAFzgbcuN1KEwOFBTjDbW4zpm50RqvrZA&lib=ME2YbkWRlb0EHiAseivp7PHA-nDy3ldf7").json()
        # print(data)
        
        newdata = []
        for i in data:
            newdata.append({"first":i['First Name'],"last": i['Last Name'],"mobile": i['Mobile Number'],"email": i['Personal Email ID'] , "Qualification":i['Qualification'],"Experience":i['Fresher/Experience ']})
        # print(newdata)
        context['data'] = newdata
        return context

class RecruitmentDelete (LoginRequiredMixin,View):
    login_url = 'hrms:login'
    def get (self, request,pk):
     form_app = Recruitment.objects.get(pk=pk)
     form_app.delete()
     return redirect('hrms:recruitmentall', permanent=True)

class Pay(LoginRequiredMixin,ListView):
    model = User
    template_name = 'hrms/payroll/index.html'
    context_object_name = 'emps'
    login_url = 'hrms:login'

class Report(LoginRequiredMixin,ListView):
    model = Attendance
    template_name = 'hrms/attendance/report/index.html'

hrms/templates/hrms/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title  %}{% endblock title %}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %} ">
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/font-awesome/css/font-awesome.css' %} ">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

  
  <link rel="stylesheet" href="{% static 'hrms/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'hrms/css/toastr.min.css' %}">
  <link rel="shortcut icon" href="{% static 'hrms/images/favicon.png' %}" />
</head>
  
<body>
  <div class="container-scroller">
    {% include "hrms/nav.html" %}
    <div class="container-fluid page-body-wrapper">
      {% include 'hrms/sidebar.html' %}
        {% block content %} {% endblock content %}
        {% include 'hrms/footer.html' %}
    </div>
  </div>
  <!-- plugins:js -->
  
  <script src="{% static 'hrms/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'hrms/vendors/js/vendor.bundle.addons.js' %}"></script>
  <script src="{% static 'hrms/js/toastr.min.js' %}"></script>
  <script src="{% static 'hrms/js/sweetalert2@8.js' %}"></script>
  <script src="{% static 'hrms/js/pay.js' %}"></script>

<!-- Include CSS for the datepicker widget -->

<!-- Include JS files for the datepicker widget -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

  {% block noty %}
  {% endblock noty %}
</body>

</html>

hrms/templates/hrms/nav.html
    {% load static %}
    <nav class="navbar default-layout bg-success col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center bg-dark">
        {% comment %} <marquee behavior="" direction="right">fasfgasd</marquee> {% endcomment %}
        <p class="display-4 mt-3 text-success" style="color:white;"><b>HR-Cracker</b></p>
        
        <a class="navbar-brand brand-logo-mini" href="{% url 'hrms:dashboard'  %}">
        
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center bg-dark">
        <marquee behavior="scroll" direction="leftt" scrollamount="10" font size=10px><b><font size=10px><i><font face=serif>POWER PASSION TRUSTED SOLUTION</marquee>
        <ul class="navbar-nav navbar-nav-right">          
          <li class="nav-item dropdown d-none d-xl-inline-block">
          {% comment %} <marquee behavior="" direction="right">hellosdv</marquee> {% endcomment %}
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text"> Hello, {{user.username | upper }} ! </span>
             
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              {% comment %} <a class="dropdown-item p-0">
                <div class="d-flex border-bottom">
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                    <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                  </div>
                </div>
              </a> {% endcomment %}
              {% comment %} <a class="dropdown-item mt-2">
                Manage Accounts
              </a>
              <a class="dropdown-item">
                Change Password
              </a>
              <a class="dropdown-item">
                Check Inbox
              </a> {% endcomment %}
              <a class="dropdown-item" href='{% url 'hrms:logout' %}'>
                Log Out
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

hrms/templates/hrms/sidebar.html
{% load static %}

<nav class="sidebar sidebar-offcanvas bg-dark" id="sidebar">
  <ul class="nav bg-dark" style="background-color:#a2ddfc; border-radius:0 0 30px 0 ">
    <li class="nav-item nav-profile" >
      <div class="nav-link bg-dark">
        <div class="user-wrapper">
          <div class="profile-image"></div>
          <div class="text-wrapper">
            {% comment %} <p class="profile-name">{{ user.username | upper }}</p> {% endcomment %}
            <div>
              <img src="{% static 'hrms/images/White Logo.png' %}"style="margin-right:60px;" width=200px>
              {% comment %} <small class="designation text-muted">Administrator</small>
              <span class="status-indicator online"></span> {% endcomment %}
            </div>
          </div>
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'hrms:employee_new' %}" class="btn btn-primary btn-block" >New Staff
          <i class="mdi mdi-plus"></i>
        </a>
        {% endif %}
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hrms:dashboard' %}">
        <i class="fa fa-dashboard" style="color: black; font-size:16px"></i>
        <span class="menu-title"  style="color: black; font-size:16px">&emsp;Dashboard</span>
      </a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hrms:employee_all' %}" aria-expanded="false" aria-controls="ui-basic">
        <i class="fa fa-user" style="color: black; font-size:16px"></i>
        <span class="menu-title" style="color: black; font-size:16px">&emsp;Employee</span>
      </a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hrms:attendance_new' %}">
        <i class="fa fa-calendar" style="color: black; font-size:16px"></i>
        <span class="menu-title" style="color: black; font-size:16px">&emsp;Attendance</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hrms:report' %}">
        <i class="fa fa-square" style="color: black; font-size:16px"></i>
        <span class="menu-title" style="color: black; font-size:16px">&emsp;Report</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hrms:leave_new' %}">
        <i class="fa fa-sign-out" style="color: black; font-size:16px"></i>
        <span class="menu-title" style="color: black; font-size:16px">&emsp;Leave</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <i class="fa fa-folder" style="color: black; font-size:16px"></i>
        <span class="menu-title" style="color: black; font-size:16px">&emsp;Department</span>
        <i class="menu-arrow"></i>
      </a>
      {% if user.is_superuser %}
      <a class="nav-link" href="{% url 'hrms:dept_new' %}" style="color: black; font-size:16px">
        <i class="fa fa-plus" style="color: black; font-size:16px"></i>&emsp;New Department
      </a>
      {% endif %}
      <hr>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          {% for dept in depts %}
          <li class="nav-item">
            <a class="nav-link" href="{{ dept.get_absolute_url }}">{{ dept.name }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hrms:recruitmentall' %}">
        <i class="fa fa-database" style="color: black; font-size:16px"></i>
        <span class="menu-title" style="color: black; font-size:16px">&emsp;Recruitment</span>
      </a>

          </li>

           <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:payroll' %}"> 
             <i class="fa fa-usd" style="color: black; font-size:16px"></i> 
             <span class="menu-title font-weight-bold" style="color: black; font-size:16px">&emsp;Payroll</span> 
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:break' %}">
              <i class="fa fa-hourglass" style="color: black; font-size:16px">&nbsp&nbsp&nbsp</i>
              <span class="menu-title" style="color: black; font-size:16px">Take A Break</span>
            </a>
          </li>

          {% comment %} <li class="nav-item">

          <li class="nav-item">
            <a class="nav-link" href="pages/icons/font-awesome.html">
              <i class="fa  fa-gears"></i>
              <span class="menu-title">&emsp;Settings</span>
            </a>
          </li> {% endcomment %}
        </ul>
      </nav>